//tag::ref-doc[]
= Pgcopy Sink

A module that writes its incoming payload to an RDBMS using the PostgreSQL COPY command.

== Input

=== Headers

=== Payload

* Any

Column expression will be evaluated against the message and the expression will usually be compatible with only one type (such as a Map or bean etc.)

== Output

N/A

== Options 

The **$$jdbc$$** $$sink$$ has the following options:

//tag::configuration-properties[]
$$pgcopy.batch-size$$:: $$Threshold in number of messages when data will be flushed to database table.$$ *($$Integer$$, default: `$$10000$$`)*
$$pgcopy.columns$$:: $$The names of the columns that shall receive data.
 Also used at initialization time to issue the DDL.$$ *($$java.util.List<java.lang.String>$$, default: `$$payload$$`)*
$$pgcopy.delimiter$$:: $$Specifies the character that separates columns within each row (line) of the file. The default is a tab character
 in text format, a comma in CSV format. This must be a single one-byte character. Using an escaped value like '\t'
 is allowed.$$ *($$String$$, default: `$$<none>$$`)*
$$pgcopy.error-table$$:: $$The name of the error table used for writing rows causing errors. The error table should have three columns
 named "table_name", "error_message" and "payload" large enough to hold potential data values.
 You can use the following DDL to create this table:
     'CREATE TABLE ERRORS (TABLE_NAME VARCHAR(255), ERROR_MESSAGE TEXT,PAYLOAD TEXT)'$$ *($$String$$, default: `$$<none>$$`)*
$$pgcopy.escape$$:: $$Specifies the character that should appear before a data character that matches the QUOTE value. The default is
 the same as the QUOTE value (so that the quoting character is doubled if it appears in the data). This must be
 a single one-byte character. This option is allowed only when using CSV format.$$ *($$Character$$, default: `$$<none>$$`)*
$$pgcopy.format$$:: $$Format to use for the copy command.$$ *($$Format$$, default: `$$<none>$$`, possible values: `TEXT`,`CSV`)*
$$pgcopy.idle-timeout$$:: $$Idle timeout in milliseconds when data is automatically flushed to database table.$$ *($$Long$$, default: `$$-1$$`)*
$$pgcopy.initialize$$:: $$'true', 'false' or the location of a custom initialization script for the table.$$ *($$String$$, default: `$$false$$`)*
$$pgcopy.null-string$$:: $$Specifies the string that represents a null value. The default is \N (backslash-N) in text format, and an
 unquoted empty string in CSV format.$$ *($$String$$, default: `$$<none>$$`)*
$$pgcopy.quote$$:: $$Specifies the quoting character to be used when a data value is quoted. The default is double-quote. This must
 be a single one-byte character. This option is allowed only when using CSV format.$$ *($$Character$$, default: `$$<none>$$`)*
$$pgcopy.table-name$$:: $$The name of the table to write into.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.datasource.driver-class-name$$:: $$Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.datasource.password$$:: $$Login password of the database.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.datasource.url$$:: $$JDBC url of the database.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.datasource.username$$:: $$Login user of the database.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

NOTE: The module also uses Spring Boot's http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-configure-datasource[DataSource support] for configuring the database connection, so properties like `spring.datasource.url` _etc._ apply.

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

For integration tests to run, start a PostgreSQL database on localhost:

```
    docker run -e POSTGRES_PASSWORD=spring -e POSTGRES_DB=test -p 5432:5432 -d postgres:latest
```

== Examples

```
java -jar pgcopy-sink.jar --tableName=names --columns=name --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver \
--spring.datasource.url='jdbc:mysql://localhost:3306/test
```

//end::ref-doc[]
